### ISSUE TITLE
Uncaught error opening DevTools in the WebDriver BiDi controlled browser

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#1975]
```
/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/utils/assert.js:22
        throw new Error(message ?? 'Internal assertion failed.');
              ^

Error: RequestWillBeSentEvent is not set
    at assert (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/utils/assert.js:22:15)
    at #getResponseStartedEvent (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/bidiMapper/domains/network/NetworkRequest.js:401:32)
    at #emitEvent (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/bidiMapper/domains/network/NetworkRequest.js:306:21)
    at #emitEventsIfReady (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/bidiMapper/domains/network/NetworkRequest.js:142:28)
    at NetworkRequest.onResponseReceivedEvent (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/bidiMapper/domains/network/NetworkRequest.js:167:32)
    at /Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/bidiMapper/domains/network/NetworkStorage.js:73:82
    at /Users/alexrudenko/src/pptr-test/node_modules/mitt/dist/mitt.js:1:255
    at Array.map (<anonymous>)
    at Object.emit (/Users/alexrudenko/src/pptr-test/node_modules/mitt/dist/mitt.js:1:239)
    at CDPClientAdapter.emit (/Users/alexrudenko/src/pptr-test/node_modules/chromium-bidi/lib/cjs/utils/EventEmitter.js:55:23)
```

@Lightning00Blade let me know if you need a repro

**Comment by OrKoN** [comment]
This is with Puppeteer 22.4.0

**Comment by Lightning00Blade** [comment]
I have fixed the issue, but still need to create a Unit test for it before closing this one.

**Comment by Lightning00Blade** [comment]
With the current implementation this should not be possible and if it is it will gets caught by the unit tests.
