### ISSUE TITLE
chromium-bidi does not handle exceptions when logging

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2317]
```
TEST-PASSED | gets operatorList, with page resources containing corrupt /CCITTFaxDecode data | in chrome
file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69
            this._reject(callback, new TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:69:36)
    at CdpCDPSession._onClosed (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:98:25)
    at Connection.onMessage (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:126:25)
    at WebSocket.<anonymous> (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/node/NodeWebSocketTransport.js:38:32)
    at callListener (C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\ws\lib\event-target.js:290:14)
    at WebSocket.onMessage (C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\ws\lib\event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\ws\lib\websocket.js:1209:20)
    at Receiver.emit (node:events:519:28)
    at Immediate.<anonymous> (C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\ws\lib\receiver.js:599:16) {
  cause: ProtocolError
      at <instance_members_initializer> (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:89:14)
      at new Callback (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:93:16)
      at CallbackRegistry.create (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/common/CallbackRegistry.js:19:26)
      at Connection._rawSend (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Connection.js:85:26)
      at CdpCDPSession.send (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/CDPSession.js:63:33)
      at CDPClientAdapter.sendCommand (file:///C:/pdfjs/botio-files-pdfjs/private/a53e51e62057105/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/BidiOverCdp.js:106:39)
      at WorkerRealm.serializeCdpObject (C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\chromium-bidi\lib\cjs\bidiMapper\modules\script\Realm.js:153:47)
      at C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\chromium-bidi\lib\cjs\bidiMapper\modules\log\LogManager.js:64:38
      at Array.map (<anonymous>)
      at C:\pdfjs\botio-files-pdfjs\private\a53e51e62057105\node_modules\chromium-bidi\lib\cjs\bidiMapper\modules\log\LogManager.js:63:45
}

```

See https://github.com/mozilla/pdf.js/issues/17961#issuecomment-2167811790

**Comment by OrKoN** [comment]
cc @sadym-chromium
