### ISSUE TITLE
Pending release fails one Puppeteer test

### ISSUE THREAD

**Issue by OrKoN** [GoogleChromeLabs/chromium-bidi#2411]
```
  Page
    Page.close
      1) should run beforeunload if asked for


  0 passing (1s)
  1 failing

  1) Page
       Page.close
         should run beforeunload if asked for:
     ProtocolError: Protocol error (browsingContext.handleUserPrompt): no such alert No dialog is showing
      at Callback.<instance_members_initializer> (packages/puppeteer-core/src/common/CallbackRegistry.ts:114:12)
      at new Callback (packages/puppeteer-core/src/common/CallbackRegistry.ts:119:3)
      at CallbackRegistry.create (packages/puppeteer-core/src/common/CallbackRegistry.ts:27:22)
      at BidiConnection.send (packages/puppeteer-core/src/bidi/Connection.ts:105:28)
      at Session.send (packages/puppeteer-core/src/bidi/core/Session.ts:134:34)
      at Session.<anonymous> (packages/puppeteer-core/src/util/decorators.ts:63:21)
      at UserPrompt.handle (packages/puppeteer-core/src/bidi/core/UserPrompt.ts:116:25)
      at UserPrompt.<anonymous> (packages/puppeteer-core/src/util/decorators.ts:63:21)
      at BidiDialog.handle (packages/puppeteer-core/src/bidi/Dialog.ts:26:24)
      at BidiDialog.accept (packages/puppeteer-core/src/api/Dialog.ts:94:16)
      at Context.<anonymous> (test/src/page.spec.ts:70:20)



Finished ["chrome","headless","webDriverBiDi"]
Add the following to TestExpectations.json to ignore the error:
[
  {
    "testIdPattern": "[page.spec] Page Page.close should run beforeunload if asked for",
    "platforms": [
      "darwin"
    ],
    "parameters": [
      "chrome",
      "headless",
      "webDriverBiDi"
    ],
    "expectations": [
      "FAIL"
    ]
  }
]
```

see https://github.com/GoogleChromeLabs/chromium-bidi/actions/runs/9904190955/job/27361363149?pr=2377

**Comment by OrKoN** [comment]
@Lightning00Blade @sadym-chromium is it due to capabilities not being set on Puppeteer side?

**Comment by Lightning00Blade** [comment]
Yes, but also Puppeteer does not currently respect that a Dialog may be handled by the time it gets the `UserPromptOpened`  event.

**Comment by Lightning00Blade** [comment]
Closed by https://github.com/GoogleChromeLabs/chromium-bidi/pull/2412
