### ISSUE TITLE
Puppeteer constantly throws: `ProtocolError: Target.setAutoAttach: Target closed.`

### ISSUE THREAD

**Issue by thiagowfx** [GoogleChromeLabs/chromium-bidi#535]
CLI Logs:

```
 puppeteer:error [
  puppeteer:error   ProtocolError: Protocol error (Target.setAutoAttach): Target closed.
  puppeteer:error       at /Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:329:24
  puppeteer:error       at new Promise (<anonymous>)
  puppeteer:error       at CDPSessionImpl.send (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:325:16)
  puppeteer:error       at ChromeTargetManager.<anonymous> (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ChromeTargetManager.js:211:25)
  puppeteer:error       at listener (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ChromeTargetManager.js:280:91)
  puppeteer:error       at /Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:232
  puppeteer:error       at Array.map (<anonymous>)
  puppeteer:error       at Object.emit (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/third_party/mitt/index.js:3:216)
  puppeteer:error       at Connection.emit (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/EventEmitter.js:87:22)
  puppeteer:error       at Connection.onMessage (/Users/tperrotta/Projects/chromium-bidi/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:173:18)
  puppeteer:error ] +0ms
```

Here's a simple way to reproduce it:

- Terminal 1: `./runBiDiServer.sh`
- Terminal 2: `python3 -m pytest tests/test_cdp.py`

In practice this functions more as a warning, because there seems to be no impact during the execution of the BiDi server.

Nonetheless, it would be nice to figure out what is its root cause and fix it.

**Comment by thiagowfx** [comment]
cc @sadym-chromium @OrKoN

**Comment by OrKoN** [comment]
Hm, I thought in Python you don't use Puppeteer? How is Puppeteer involved in the repro?

**Comment by OrKoN** [comment]
The root cause seems to be that targets get closed while Puppeteer is trying to initialise them. The error should be caught and only show up in the debug log.

**Comment by OrKoN** [comment]
```
  // 1. Launch Chromium (using Puppeteer for now).
  // Puppeteer should have downloaded Chromium during the installation.
  // Use Puppeteer's logic of launching browser as well.
  const browser = await puppeteer.launch(browserLaunchOptions);

  // No need in Puppeteer being connected to browser.
  browser.disconnect();

```

Probably the test does not run till the setup is done and starts running tests while this is running. You should use the `@puppeteer/browsers` launch function here now.

**Comment by thiagowfx** [comment]
https://github.com/GoogleChromeLabs/chromium-bidi/pull/538

**Comment by thiagowfx** [comment]
Confirming I cannot reproduce this anymore. Fixed indeed.
